### PR TITLE
Test master branch on Travis

### PR DESCRIPTION
**Pull request by tarcieri**

### CODE REVIEW

**Comment by tarcieri** [comment]
@iqulus r+

**Comment by ghost** [comment]
:pushpin: Commit 9349ea9 has been approved by `tarcieri`

**Comment by ghost** [comment]
:hourglass: Testing commit 9349ea9 with merge a2a7396...

**Comment by tarcieri** [comment]
@iqulus retry

**Comment by ghost** [comment]
:hourglass: Testing commit 9349ea9 with merge 8cf97b6...

**Comment by tarcieri** [comment]
@iqulus retry

**Comment by tarcieri** [comment]
@iqulus r+

**Comment by tarcieri** [comment]
@iqulus r+

**Comment by tarcieri** [comment]
@iqulus r+

**Comment by ghost** [comment]
:bulb: This pull request was already approved, no need to approve it again.
- This pull request is currently being tested. If there's no response from the continuous integration service, you may use `retry` to trigger a build again.

**Comment by ghost** [comment]
:pushpin: Commit 9349ea9 has been approved by `tarcieri`

**Comment by tarcieri** [comment]
@iqulus retry

**Comment by ghost** [comment]
:hourglass: Testing commit 9349ea9 with merge 3df638b...

**Comment by tarcieri** [comment]
@iqulus retry

**Comment by ghost** [comment]
:hourglass: Testing commit 9349ea9 with merge 65277c8...

**Pull request closed without merging**
